#+begin_export latex
In this Tutorial we calculate and plot the matching statistics, $\ms$,
and the match lengths, $\ml$. We begin by simulating a pair of
sequences using the program \ty{stan}, which is intended for
simulating target and neighbor sequences. By default, the target
sequence is 10\,kb long and contains a 1\,kb insertion at its center;
the neighbor sequence is 9\,kb long as it lacks the insertion, but is
otherwise homologous to the target. With the option \ty{-o} \ty{stan}
overwrites an existing pair of directories containing targets and
neighbors.
#+end_export
#+begin_src sh <<tut.sh>>=
  stan -t 1 -n 1 -o
#+end_src
#+begin_export latex
We run \ty{mast} using the target as the query, $q$, and the neighbor
as the reference, $r$. The results are redirected to the file
\ty{mast.out}.
#+end_export
#+begin_src sh <<tut.sh>>=
  mast targets/t1.fasta neighbors/n1.fasta > mast.out
#+end_src
#+begin_export latex
We take a look at the top of the results file. Since this is a
stochastic simulation, your results are bound to differ from mine.
#+end_export
#+begin_src sh <<tut.sh>>=
  head mast.out
#+end_src
#+begin_export latex
\begin{verbatim}
# Query: t1; reference: n1
# i     ms[i]   ml[i]
1       6       6
2       27      5
3       26      4
4       25      3
5       24      2
6       23      1
7       22      0
8       21      21
\end{verbatim}
#+end_export
#+begin_export latex
To plot $\ms$ and $\ml$, we extract two sets of $(x,y)$ values that we
label ``ms'' or ``ml'' in the third column and store in the file
\ty{mast.dat}.
#+end_export
#+begin_src sh <<tut.sh>>=
  tail -n +3 mast.out |
      awk '{print $1, $2, "ms"}' >  mast.dat
  tail -n +3 mast.out |
      awk '{print $1, $3, "ml"}' >> mast.dat
#+end_src
#+begin_export latex
We can now plot $\ms$ and $\ml$ to get Figure~\ref{fig:ms}. It shows
that the values of $\ms$ and $\ml$ are largely indistinguishable. The
exception is the central 1\,kb deletion in $q$. Here $\ms$ and $\ml$
are both small, but differ in numerical detail. Visually at least, the
difference amounts to very little.
#+end_export
#+begin_src sh <<tut.sh>>=
  plotLine -x "Position" -y "Length" mast.dat
#+end_src
#+begin_export latex
\begin{figure}
  \begin{center}
    \scalebox{0.9}{\includegraphics{../tutorial/mast}}
  \end{center}
  \caption{The matching statistics, $\ms$, and the match length, $\ml$
    along a simulated 10\,kb pair of sequences, where the query
    contains a centered 1\,kb instertion.}\label{fig:ms}
\end{figure}
#+end_export
