#+begin_export latex
\section{Introduction}
The program \ty{mast} demonstrates the calculation of match lengths
from FASTA-formatted sequences. To make the output transparent, we
take the input as a regular string rather than a DNA sequence that
might need to be complemented. The program takes as input one query
file in FASTA format and an arbitrary number of reference files in
FASTA format. For each sequence in the query file, the matching
calculations are carried out for each sequence in a given reference
file.
\section{Implementation}
The outline of \ty{mast} contains hooks for imports, functions, and
the logic of the main function.
\bpr{mast}{pr:mas}
#+end_export
#+begin_src go <<mast.go>>=
  package main

  import (
	  //<<Imports, Pr. \ref{pr:mas}>>
  )

  //<<Functions, Pr. \ref{pr:mas}>>
  func main() {
	  //<<Main function, Pr. \ref{pr:mas}>>
  }
#+end_src
#+begin_export latex
\epr In the main function we interact with the user, read the query
sequences, and iterate over the input files.
#+end_export
#+begin_src go <<Main function, Pr. \ref{pr:mas}>>=
  //<<User interaction, Pr. \ref{pr:mas}>>
  //<<Read query sequences, Pr. \ref{pr:mas}>>
  //<<Iterate over reference files, Pr. \ref{pr:mas}>>
#+end_src
#+begin_export latex
The first step in our user interaction is to prepare the messages
generated by the \ty{log} package, which is typically called to abort
with message. Then we set the usage, declare the
options, and parse them.
#+end_export
#+begin_src go <<User interaction, Pr. \ref{pr:mas}>>=
  clio.PrepLog("mast")
  //<<Set usage, Pr. \ref{pr:mas}>>
  //<<Declare options, Pr. \ref{pr:mas}>>
  //<<Parse options, Pr. \ref{pr:mas}>>
#+end_src
#+begin_export latex
We imports \ty{clio}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mas}>>=
  "github.com/evolbioinf/clio"
#+end_src
#+begin_export latex
The usage consists of three parts: The actual usage message, an
explanation of the purpose of \ty{mast}, and an example command.
#+end_export
#+begin_src go <<Set usage, Pr. \ref{pr:mas}>>=
  u := "mast [option]... q.fasta [r1.fasta]..."
  p := "Calculate matching statistics and " +
	  "match lengths for q w.r.t. r"
  e := "mast q.fasta r.fasta"
  clio.Usage(u, p, e)
#+end_src
#+begin_export latex
We declare only one option, the version.
#+end_export
#+begin_src go <<Declare options, Pr. \ref{pr:mas}>>=
  optV := flag.Bool("v", false, "version")
#+end_src
#+begin_export latex
We import \ty{flag}.
#+end_export
#+begin_src sh <<Imports, Pr. \ref{pr:mas}>>=
  "flag"
#+end_src
#+begin_export latex
We parse our single option, the version. We also respond to it
immediately, as a request for the version stops the program after the
version has been printed.
#+end_export
#+begin_src go <<Parse options, Pr. \ref{pr:mas}>>=
  flag.Parse()
  if *optV {
	  util.Version("mast")
  }
#+end_src
#+begin_export latex
We import \ty{util}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mas}>>=
  "github.com/evolbioinf/mast/util"
#+end_src
#+begin_export latex
The remaining tokens on the command line are interpreted as input
files. If there are none, the user did not supply a query, so we
kindly ask for one. Otherwise, we store the query sequences.
#+end_export
#+begin_src go <<Read query sequences, Pr. \ref{pr:mas}>>=
  files := flag.Args()
  if len(files) < 1 {
	  m := "please provide the " +
		  "name of a query file"
	  log.Fatal(m)
  }
  //<<Store query sequences, Pr. \ref{pr:mas}>>
#+end_src
#+begin_export latex
We import \ty{log}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mas}>>=
  "log"
#+end_src
#+begin_export latex
We store the query sequences in a slice of pointers to \ty{Sequence}.
#+end_export
#+begin_src go <<Store query sequences, Pr. \ref{pr:mas}>>=
  qseqs := make([]*fasta.Sequence, 0)
  file, err := os.Open(files[0])
  if err != nil {
	  log.Fatal(err)
  }
  scanner := fasta.NewScanner(file)
  for scanner.ScanSequence() {
	  qseqs = append(qseqs, scanner.Sequence())
  }
#+end_src
#+begin_export latex
We import \ty{fasta} and \ty{os}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mas}>>=
  "github.com/evolbioinf/fasta"
  "os"
#+end_src
#+begin_export latex
The remaining files are reference files. We apply the function
\ty{parse} to each one of them and pass the query sequences as
arguments to \ty{parse}.
#+end_export
#+begin_src go <<Iterate over reference files, Pr. \ref{pr:mas}>>=
  refSeqs := files[1:]
  clio.ParseFiles(refSeqs, parse, qseqs)
#+end_src
#+begin_export latex
Inside \ty{parse}, we retrieve the query sequences, iterate over the
sequences in the current file, and compare each query to each
reference.
#+end_export
#+begin_src go <<Functions, Pr. \ref{pr:mas}>>=
  func parse(r io.Reader, args ...interface{}) {
	  qseqs := args[0].([]*fasta.Sequence)
	  sc := fasta.NewScanner(r)
	  for sc.ScanSequence() {
		  rseq := sc.Sequence()
		  for _, qseq := range qseqs {
			  //<<Compare query and reference, Pr. \ref{pr:mas}>>
		  }
	  }
  }
#+end_src
#+begin_export latex
We import \ty{io}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mas}>>=
  "io"
#+end_src
#+begin_export latex
When comparing the current query/reference pair, we calculate the
match lengths, calculate the matching statistics, and print the output.
#+end_export
#+begin_src go <<Compare query and reference, Pr. \ref{pr:mas}>>=
  //<<Calculate match lengths, Pr. \ref{pr:mas}>>
  //<<Calculate matching statistics, Pr. \ref{pr:mas}>>
  //<<Print output, Pr. \ref{pr:mas}>>
#+end_src
#+begin_export latex
We calculate the match lengths according to Algorithm~\ref{alg:ml}. We
begin by setting the sequence data to $q$ and $r$ for easy handling,
and allocate space for $\ml$. Then we calculate the enhanced suffix
array of $r$, before embarking on the two phases of the algorithm
proper, the matching phase and the interpolation phase.
#+end_export
#+begin_src go <<Calculate match lengths, Pr. \ref{pr:mas}>>=
  q := qseq.Data()
  r := rseq.Data()
  ml := make([]int, len(q))
  esa := esa.MakeEsa(r)
  //<<Matching phase, Pr. \ref{pr:mas}>>
  //<<Interpolation phase, Pr. \ref{pr:mas}>>
#+end_src
#+begin_export latex
We import \ty{esa}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mas}>>=
  "github.com/evolbioinf/esa"
#+end_src
#+begin_export latex
In the matching phase we skip across $q$ according to the matches we
find (Algorithm~\ref{alg:ml}, lines 3--7).
#+end_export
#+begin_src go <<Matching phase, Pr. \ref{pr:mas}>>=
  i := 0
  for i < len(q) {
	  l := esa.MatchPref(q[i:]).L
	  ml[i] = l
	  i += l + 1
  }
#+end_src
#+begin_export latex
In the interpolation phase we add the missing match lengths to $\ml$
(Algorithm~\ref{alg:ml}, lines 8--12).
#+end_export
#+begin_src go <<Interpolation phase, Pr. \ref{pr:mas}>>=
  for i := 1; i < len(ml); i++ {
	  if ml[i] < ml[i-1]-1 {
		  ml[i] = ml[i-1]-1
	  }
  }
#+end_src
#+begin_export latex
We calculate the matching statistics by calling \ty{MatchPref} on
every query position. This leads to a quadratic run time, which is
fast enough for the purposes of this demo program, but could be
avoided using suffix links.
#+end_export
#+begin_src go <<Calculate matching statistics, Pr. \ref{pr:mas}>>=
  ms := make([]int, len(q))
  for i := 0; i < len(q); i++ {
	  ms[i] = esa.MatchPref(q[i:]).L
  }
#+end_src
#+begin_export latex
We print the names of the current query and reference, before we print
their matching statistics and match lengths side by side.
#+end_export
#+begin_src go <<Print output, Pr. \ref{pr:mas}>>=
  fmt.Printf("# Query: %s; reference: %s\n",
	  qseq.Header(), rseq.Header())
  fmt.Printf("# i\tms[i]\tml[i]\n")
  for i := 0; i < len(ml); i++ {
	  fmt.Printf("%d\t%d\t%d\n", i+1, ms[i], ml[i])
  }
#+end_src
#+begin_export latex
We import \ty{fmt}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mas}>>=
  "fmt"
#+end_src
#+begin_export latex
We're done writing \ty{mast}, time to test it.
\section{Testing}
The outline of our testing code contains hooks for imports and the
testing logic.
#+end_export
#+begin_src go <<mast_test.go>>=
  package main

  import (
	  //<<Testing imports, Pr. \ref{pr:mas}>>
  )

  func TestMas(t *testing.T) {
	  //<<Testing, Pr. \ref{pr:mas}>>
  }
#+end_src
#+begin_export latex
We import testing.
#+end_export
#+begin_src go <<Testing imports, Pr. \ref{pr:mas}>>=
  "testing"
#+end_src
#+begin_export latex
We construct a set of tests and then iterate over them.
#+end_export
#+begin_src go <<Testing, Pr. \ref{pr:mas}>>=
  tests := make([]*exec.Cmd, 0)
  //<<Construct tests, Pr. \ref{pr:mas}>>
  for i, test := range tests {
	  //<<Run test, Pr. \ref{pr:mas}>>
  }
#+end_src
#+begin_export latex
We import \ty{exec}.
#+end_export
#+begin_src go <<Testing imports, Pr. \ref{pr:mas}>>=
  "os/exec"
#+end_src
#+begin_export latex
We construct two tests with two pairs of query and reference
sequences.
#+end_export
#+begin_src go <<Construct tests, Pr. \ref{pr:mas}>>=
  test := exec.Command("./mast", "q1.fasta", "r1.fasta")
  tests = append(tests, test)
  test = exec.Command("./mast", "q2.fasta", "r2.fasta")
  tests = append(tests, test)
#+end_src
#+begin_export latex
When running a test, we compare the output we get with the output we
want, which is stored in files \ty{r1.txt} and \ty{r2.txt}.
#+end_export
#+begin_src go <<Run test, Pr. \ref{pr:mas}>>=
  get, err := test.Output()
  if err != nil {
	  t.Error(err)
  }
  f := "r" + strconv.Itoa(i+1) + ".txt"
  want, err := os.ReadFile(f)
  if err != nil {
	  t.Error(err)
  }
  if !bytes.Equal(get, want) {
	  t.Errorf("get:\n%s\nwant:\n%s\n", get, want)
  }
#+end_src
#+begin_export latex
We import \ty{strconv}, \ty{os}, and \ty{bytes}.
#+end_export
#+begin_src go <<Testing imports, Pr. \ref{pr:mas}>>=
  "strconv"
  "os"
  "bytes"
#+end_src


