NW = $(shell which noweb)

all : util

util: util.go
	go build util.go
util.go: util.org
	if [ $(NW) != "" ]; then\
		awk -f ../scripts/preTangle.awk util.org | bash ../scripts/org2nw | notangle -Rutil.go | gofmt > util.go;\
	fi
.PHONY: test
test: 
	echo "util is not tested"
tangle: util.go

clean:
	rm -f *.go
